#!/usr/bin/env bash
# Installs and configures HAProxy on my lb-01 server
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get install haproxy=2.6.\*

mkdir -p /etc/haproxy/
printf %s "frontend alex-frontend
		bind :80
		default_backend alex-backends

	   backend alex-backends
	 	server 129276-web-01 18.209.223.27
		server 129276-web-02 100.25.118.39
	" >> /etc/haproxy/haproxy.cfg
