#!/usr/bin/bash
# configures firewall so that it blocks all incoming traffic
apt-get install ufw
ufw default allow outgoing
ufw default deny incoming
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow from 0.0.0.0 to any port 3306
ufw enable
