#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely
# Requirements:
#   In between each iteration of the loop,a sleep of 2.

while true
do
  echo "To infinity and beyond"
  sleep 2
done
