#!/usr/bin/env bash
# Displays:
# The content of the current directory
# In list format.
# Where Only displays part of the name after the first dash is displayed. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
